language: csharp
mono: none
dist: xenial
addons:
    snaps:
      - name: dotnet-sdk
        confinement: classic
        channel: 5.0/stable
env:
    global:
      - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
install:
    - export PATH="$PATH:/home/travis/.dotnet/tools"
    - export PATH="$PATH:$HOME/.local/bin"
    - pip install --user awscli
    - sudo snap alias dotnet-sdk.dotnet dotnet
    - chmod -R a+x scripts
script:
    - dotnet --version
    - dotnet restore
    - dotnet build
    - dotnet test test/NosCore.ReverseProxy.Tests -v m --no-build
deploy:
  cleanup: true
  provider: script
  script: sudo bash ./scripts/docker-publish.sh
  on:
    branch: master
