name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Run Unit Tests
      run: |
        dotnet restore
        dotnet build
        dotnet test test/ReverseProxy.Tests -v m
    
    - name: Login to DockerHub
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - run: dotnet test --runtime linux-musl-x64 --filter TestCategory=SomethingAsDotnetBuildDoesntWorkAnymore
    - name: Build, tag, and push image
      if: github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v2
      with:
        file: ./deploy/Dockerfile
        push: true
        tags: noscoreio/noscore.reverseproxy:latest
